# Runs on push to master
## Manages content deployment for garden.joshpress.net

name: Meadow Halloween [CD]

on:
  push:
    branches: [master]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      # Trigger vercel webhook
      - name: Vercel Deploy
        uses: wei/curl@master
        with:
          args: ${{ secrets.VERCEL_DEPLOY_HOOK }}
